version: '2'
services:
  wordpress:
    build: .
    volumes:
      - ./content:/var/www/content
    environment:
      DOCKER_ENV: development
      WP_DB_NAME: wp
      WP_DB_USER: wp
      WP_DB_PASSWORD: wp
      WP_DB_HOST: mysql
      WP_SITEURL: http://localhost:8080
    ports:
      - "8080:80"
  mysql:
    image: mariadb:5.5
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
